version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: sunday
      time: '03:00'
      timezone: Europe/Prague
    versioning-strategy: increase
    groups:
      minors-and-patches:
        applies-to: version-updates
        patterns: ['*']
        update-types: ['minor', 'patch']
    ignore:
      - dependency-name: '@dnd-kit/helpers'
        versions: ['>=0.3.0']
      - dependency-name: 'zod'
        versions: ['>=4.4.0']
